package adapters

import (
	"fmt"
	"ogsShell/core/services/theme"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type HyprlandAdapter struct {
	customConfigPath string
}

func NewHyprlandAdapter(customPath ...string) *HyprlandAdapter {
	p := ""
	if len(customPath) > 0 {
		p = customPath[0]
	}
	return &HyprlandAdapter{customConfigPath: p}
}

func (a *HyprlandAdapter) ID() string   { return "hyprland" }
func (a *HyprlandAdapter) Name() string { return "Hyprland Compositor" }

func (a *HyprlandAdapter) getColorsConfPath() string {
	if a.customConfigPath != "" {
		return a.customConfigPath
	}
	homeDir, _ := os.UserHomeDir()
	return filepath.Join(homeDir, ".config", "hypr", "colors.conf")
}

func (a *HyprlandAdapter) IsInstalled() bool {
	if _, err := exec.LookPath("hyprctl"); err == nil {
		return true
	}
	confPath := a.getColorsConfPath()
	_, err := os.Stat(confPath)
	return err == nil
}

func (a *HyprlandAdapter) Apply(palette *theme.ThemePalette) error {
	accent := strings.TrimPrefix(palette.Colors["accent"], "#")
	if accent == "" {
		accent = "89b4fa"
	}
	bg := strings.TrimPrefix(palette.Colors["bg"], "#")
	if bg == "" {
		bg = "1e1e2e"
	}
	surface := strings.TrimPrefix(palette.Colors["surface"], "#")
	if surface == "" {
		surface = "313244"
	}
	fg := strings.TrimPrefix(palette.Colors["fg"], "#")
	if fg == "" {
		fg = "cdd6f4"
	}
	red := strings.TrimPrefix(palette.Colors["red"], "#")
	if red == "" {
		red = "f38ba8"
	}

	// 1. Live recolor active window border in running Hyprland session
	borderArg := fmt.Sprintf("rgba(%sff) rgba(%sff) 45deg", accent, surface)
	_ = exec.Command("hyprctl", "keyword", "general:col.active_border", borderArg).Run()
	_ = exec.Command("hyprctl", "keyword", "general:col.inactive_border", fmt.Sprintf("rgba(%sff)", surface)).Run()

	// 2. Write colors.conf
	confPath := a.getColorsConfPath()
	dir := filepath.Dir(confPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	content := fmt.Sprintf(`# Auto-generated by ogsShell for %s
$background = rgba(%sff)
$surface = rgba(%sff)
$foreground = rgba(%sff)
$accent = rgba(%sff)
$error = rgba(%sff)
$active_border = %s
`, palette.Name, bg, surface, fg, accent, red, borderArg)

	tmpPath := fmt.Sprintf("%s.tmp", confPath)
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return err
	}

	return os.Rename(tmpPath, confPath)
}
