# === OgsShell-qs Tmux Colors (Rosé Pine) ===
set -g @minimal-tmux-fg "#191724"
set -g @minimal-tmux-bg "#EBBCBA"
set -g @minimal-tmux-prefix-fg "#191724"
set -g @minimal-tmux-prefix-bg "#F6C177"
set -g pane-border-style "fg=#26233A"
set -g pane-active-border-style "fg=#EBBCBA"
