# Everforest Dark theme for btop (OgsShell-qs)

theme[main_bg]=""
theme[main_fg]="#d3c6aa"
theme[title]="#a7c080"
theme[hi_fg]="#83c092"
theme[selected_bg]="#475258"
theme[selected_fg]="#d3c6aa"
theme[inactive_fg]="#7a8478"
theme[proc_misc]="#7fbbb3"

theme[cpu_box]="#3a454a"
theme[mem_box]="#3a454a"
theme[net_box]="#3a454a"
theme[proc_box]="#3a454a"
theme[div_line]="#343f44"

theme[temp_start]="#a7c080"
theme[temp_mid]="#dbbc7f"
theme[temp_end]="#e67e80"

theme[cpu_start]="#a7c080"
theme[cpu_mid]="#7fbbb3"
theme[cpu_end]="#e67e80"

theme[free_start]="#a7c080"
theme[free_mid]="#83c092"
theme[free_end]="#7fbbb3"

theme[cached_start]="#7fbbb3"
theme[cached_mid]="#d699b6"
theme[cached_end]="#a7c080"

theme[available_start]="#dbbc7f"
theme[available_mid]="#e69875"
theme[available_end]="#a7c080"

theme[used_start]="#e67e80"
theme[used_mid]="#e69875"
theme[used_end]="#d699b6"

theme[download_start]="#a7c080"
theme[download_mid]="#7fbbb3"
theme[download_end]="#d699b6"

theme[upload_start]="#dbbc7f"
theme[upload_mid]="#e69875"
theme[upload_end]="#e67e80"
