# Nord theme for btop (OgsShell-qs)

theme[main_bg]=""
theme[main_fg]="#eceff4"
theme[title]="#88c0d0"
theme[hi_fg]="#81a1c1"
theme[selected_bg]="#4c566a"
theme[selected_fg]="#eceff4"
theme[inactive_fg]="#4c566a"
theme[proc_misc]="#81a1c1"

theme[cpu_box]="#4c566a"
theme[mem_box]="#4c566a"
theme[net_box]="#4c566a"
theme[proc_box]="#4c566a"
theme[div_line]="#3b4252"

theme[temp_start]="#88c0d0"
theme[temp_mid]="#ebcb8b"
theme[temp_end]="#bf616a"

theme[cpu_start]="#88c0d0"
theme[cpu_mid]="#81a1c1"
theme[cpu_end]="#bf616a"

theme[free_start]="#a3be8c"
theme[free_mid]="#8fbcbb"
theme[free_end]="#88c0d0"

theme[cached_start]="#88c0d0"
theme[cached_mid]="#81a1c1"
theme[cached_end]="#b48ead"

theme[available_start]="#ebcb8b"
theme[available_mid]="#d08770"
theme[available_end]="#88c0d0"

theme[used_start]="#bf616a"
theme[used_mid]="#d08770"
theme[used_end]="#b48ead"

theme[download_start]="#a3be8c"
theme[download_mid]="#88c0d0"
theme[download_end]="#b48ead"

theme[upload_start]="#ebcb8b"
theme[upload_mid]="#d08770"
theme[upload_end]="#bf616a"
