# Rosé Pine theme for btop (OgsShell-qs)

theme[main_bg]=""
theme[main_fg]="#e0def4"
theme[title]="#ebbcba"
theme[hi_fg]="#c4a7e7"
theme[selected_bg]="#403d52"
theme[selected_fg]="#e0def4"
theme[inactive_fg]="#6e6a86"
theme[proc_misc]="#c4a7e7"

theme[cpu_box]="#26233a"
theme[mem_box]="#26233a"
theme[net_box]="#26233a"
theme[proc_box]="#26233a"
theme[div_line]="#21202e"

theme[temp_start]="#9ccfd8"
theme[temp_mid]="#f6c177"
theme[temp_end]="#eb6f92"

theme[cpu_start]="#9ccfd8"
theme[cpu_mid]="#ebbcba"
theme[cpu_end]="#eb6f92"

theme[free_start]="#31748f"
theme[free_mid]="#9ccfd8"
theme[free_end]="#c4a7e7"

theme[cached_start]="#9ccfd8"
theme[cached_mid]="#ebbcba"
theme[cached_end]="#c4a7e7"

theme[available_start]="#f6c177"
theme[available_mid]="#ebbcba"
theme[available_end]="#9ccfd8"

theme[used_start]="#eb6f92"
theme[used_mid]="#f6c177"
theme[used_end]="#c4a7e7"

theme[download_start]="#31748f"
theme[download_mid]="#9ccfd8"
theme[download_end]="#ebbcba"

theme[upload_start]="#f6c177"
theme[upload_mid]="#ebbcba"
theme[upload_end]="#eb6f92"
