# Tokyo Night theme for btop (OgsShell-qs)

theme[main_bg]=""
theme[main_fg]="#c0caf5"
theme[title]="#7aa2f7"
theme[hi_fg]="#2ac3de"
theme[selected_bg]="#33384d"
theme[selected_fg]="#c0caf5"
theme[inactive_fg]="#565f89"
theme[proc_misc]="#bb9af7"

theme[cpu_box]="#24283b"
theme[mem_box]="#24283b"
theme[net_box]="#24283b"
theme[proc_box]="#24283b"
theme[div_line]="#1f2335"

theme[temp_start]="#7aa2f7"
theme[temp_mid]="#e0af68"
theme[temp_end]="#f7768e"

theme[cpu_start]="#7aa2f7"
theme[cpu_mid]="#bb9af7"
theme[cpu_end]="#f7768e"

theme[free_start]="#9ece6a"
theme[free_mid]="#7dcfff"
theme[free_end]="#7aa2f7"

theme[cached_start]="#7aa2f7"
theme[cached_mid]="#bb9af7"
theme[cached_end]="#f7768e"

theme[available_start]="#e0af68"
theme[available_mid]="#ff9e3b"
theme[available_end]="#7aa2f7"

theme[used_start]="#f7768e"
theme[used_mid]="#ff9e3b"
theme[used_end]="#bb9af7"

theme[download_start]="#9ece6a"
theme[download_mid]="#7aa2f7"
theme[download_end]="#bb9af7"

theme[upload_start]="#e0af68"
theme[upload_mid]="#ff9e3b"
theme[upload_end]="#f7768e"
