# === Minimal Tmux Theme (CATPPUCCIN MOCHA) ===
set -g @minimal-tmux-fg "#1E1E2E"
set -g @minimal-tmux-bg "#CBA6F7"
set -g @minimal-tmux-justify "absolute-centre"
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true
set -g @minimal-tmux-expanded-icon "󰊓 "
set -g @minimal-tmux-show-expanded-icon-for-all-tabs true

set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
set -g @minimal-tmux-indicator false

set -g @minimal-tmux-status-left-extra "#{?client_prefix,#[fg=#F38BA8]#[bg=#F38BA8]#[fg=#1E1E2E]#[bold] tmux #[default]#[fg=#F38BA8],#[fg=#CBA6F7]#[bg=#CBA6F7]#[fg=#1E1E2E]#[bold] tmux #[default]#[fg=#CBA6F7]} "
set -g @minimal-tmux-status-right-extra " #{cpu_percentage}   #{ram_percentage}  󰘬 #(git -C #{pane_current_path} branch --show-current 2>/dev/null) "

set -g status-right-length 150
set -g status-left-length 150
