# === OgsShell-qs Tmux Colors (Catppuccin Mocha) ===
set -g @minimal-tmux-fg "#1E1E2E"
set -g @minimal-tmux-bg "#CBA6F7"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#CBA6F7"
