# === Minimal Tmux Theme (NORD) ===
set -g @minimal-tmux-fg "#2E3440"
set -g @minimal-tmux-bg "#88C0D0"
set -g @minimal-tmux-justify "absolute-centre"
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true
set -g @minimal-tmux-expanded-icon "󰊓 "
set -g @minimal-tmux-show-expanded-icon-for-all-tabs true

set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
set -g @minimal-tmux-indicator false

set -g @minimal-tmux-status-left-extra "#{?client_prefix,#[fg=#BF616A]#[bg=#BF616A]#[fg=#2E3440]#[bold] tmux #[default]#[fg=#BF616A],#[fg=#88C0D0]#[bg=#88C0D0]#[fg=#2E3440]#[bold] tmux #[default]#[fg=#88C0D0]} "
set -g @minimal-tmux-status-right-extra " #{cpu_percentage}   #{ram_percentage}  󰘬 #(git -C #{pane_current_path} branch --show-current 2>/dev/null) "

set -g status-right-length 150
set -g status-left-length 150
